### PR TITLE
Upgrading deps, removing aws utils

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by laughedelic** [comment]
:ok_hand: 
I have removed all aws-related code from here. I **guess** it's not used anywhere. Am I right?

**Comment by eparejatobes** [comment]
I really don't know. As long as we do this in a new non-snapshot version there shouldn't be any issue

**Comment by eparejatobes** [comment]
anything against merging this? @pablopareja ?

**Comment by pablopareja** [comment]
mmm I guess not...
However I think that this stuff might still be used in a bunch of _sort-of-old_ programs spread across different repositories.  Anyway, in the case where one of them has to be used again I assume there will be a more up-to-date way of achieving a equivalent behavior.

**Comment by laughedelic** [comment]
Ok. The I'm merging this and releasing a new version

**Pull request merged**
